name: Trigger auto deployment for test2304container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test2304container-AutoDeployTrigger-092eb19b-4c81-4b53-adec-ec4a9c71ed78.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TEST2304CONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEST2304CONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEST2304CONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: myflasktestcontainer.azurecr.io
          registryUsername: ${{ secrets.TEST2304CONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEST2304CONTAINER_REGISTRY_PASSWORD }}
          containerAppName: test2304container
          resourceGroup: JameVM
          imageToBuild: myflasktestcontainer.azurecr.io/test2304container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


